=> wandb run name : resnet18_leuven_bce resnet18_leuven_bce
=> torch version : 1.10.1+cu111
=> ngpus : 2
=> modeling the network resnet18 ...
=> num of params: 53107337 (202M)
=> building the oprimizer ...
=> building the dataloader ...
=> building the criterion ...
=> starting training engine ...
Traceback (most recent call last):
  File "/home/siddsuresh97/Projects/cs839-autoencoder/train.py", line 251, in <module>
    main(args)
  File "/home/siddsuresh97/Projects/cs839-autoencoder/train.py", line 99, in main
    main_worker(ngpus_per_node, args)
  File "/home/siddsuresh97/Projects/cs839-autoencoder/train.py", line 173, in main_worker
    do_train(train_loader, model, criterion, optimizer, epoch, args, leuven_bce_transposed)
  File "/home/siddsuresh97/Projects/cs839-autoencoder/train.py", line 218, in do_train
    output, leuven_output = model(input)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddsuresh97/Projects/cs839-autoencoder/models/resnet.py", line 38, in forward
    leuven_normspace = self.leuven_encoder(x)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddsuresh97/Projects/cs839-autoencoder/models/resnet.py", line 96, in forward
    x = self.encoder(x)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/siddsuresh97/packages/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1835008x7 and 2048x2048)